package me.mrCookieSlime.Slimefun.Setup;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import me.mrCookieSlime.Slimefun.Lists.SlimefunItems;
import me.mrCookieSlime.Slimefun.Objects.Research;
import me.mrCookieSlime.Slimefun.api.Slimefun;

public final class ResearchSetup {
	
	private ResearchSetup() {}

	public static void setupResearches() {
	    Slimefun.registerResearch(new Research(0, "Мои любимые трости", 1), SlimefunItems.GRANDMAS_WALKING_STICK, SlimefunItems.GRANDPAS_WALKING_STICK);
	    Slimefun.registerResearch(new Research(1, "Портативный крафтер", 1), SlimefunItems.PORTABLE_CRAFTER);
	    Slimefun.registerResearch(new Research(2, "Печенье судьбы", 1), SlimefunItems.FORTUNE_COOKIE);
	    Slimefun.registerResearch(new Research(4, "Портативный мусорный ящик", 2), SlimefunItems.PORTABLE_DUSTBIN);
	    Slimefun.registerResearch(new Research(5, "Вяленое мясо", 2), SlimefunItems.BEEF_JERKY, SlimefunItems.FISH_JERKY, SlimefunItems.RABBIT_JERKY, SlimefunItems.MUTTON_JERKY, SlimefunItems.CHICKEN_JERKY, SlimefunItems.PORK_JERKY);
	    Slimefun.registerResearch(new Research(6, "Создание новой брони", 2), SlimefunItems.ARMOR_FORGE);
	    Slimefun.registerResearch(new Research(8, "Осколки Незера и Эндера", 3), SlimefunItems.MAGIC_LUMP_1, SlimefunItems.MAGIC_LUMP_2, SlimefunItems.MAGIC_LUMP_3, SlimefunItems.ENDER_LUMP_1, SlimefunItems.ENDER_LUMP_2, SlimefunItems.ENDER_LUMP_3);
	    Slimefun.registerResearch(new Research(9, "Эндер-рюкзак", 4), SlimefunItems.ENDER_BACKPACK);
	    Slimefun.registerResearch(new Research(7, "Светящаяся броня", 3), SlimefunItems.GLOWSTONE_HELMET, SlimefunItems.GLOWSTONE_CHESTPLATE, SlimefunItems.GLOWSTONE_LEGGINGS, SlimefunItems.GLOWSTONE_BOOTS);
	    Slimefun.registerResearch(new Research(10, "Эндер-броня", 4), SlimefunItems.ENDER_HELMET, SlimefunItems.ENDER_CHESTPLATE, SlimefunItems.ENDER_LEGGINGS, SlimefunItems.ENDER_BOOTS);
	    Slimefun.registerResearch(new Research(11, "Магическое око Эндера", 4), SlimefunItems.MAGIC_EYE_OF_ENDER);
	    Slimefun.registerResearch(new Research(12, "Волшебный сахар", 4), SlimefunItems.MAGIC_SUGAR);
	    Slimefun.registerResearch(new Research(13, "Вяленая плоть", 5), SlimefunItems.MONSTER_JERKY);
	    Slimefun.registerResearch(new Research(14, "Слизневая броня", 5), SlimefunItems.SLIME_HELMET, SlimefunItems.SLIME_CHESTPLATE, SlimefunItems.SLIME_LEGGINGS, SlimefunItems.SLIME_BOOTS);
	    Slimefun.registerResearch(new Research(15, "Меч обезглавливания", 6), SlimefunItems.SWORD_OF_BEHEADING);
	    Slimefun.registerResearch(new Research(16, "Электромонтажные работы", 8), SlimefunItems.BASIC_CIRCUIT_BOARD);
	    Slimefun.registerResearch(new Research(17, "Продвинутое электричество", 9), SlimefunItems.ADVANCED_CIRCUIT_BOARD);
	    Slimefun.registerResearch(new Research(18, "Горячая выплавка", 10), SlimefunItems.SMELTERY);
	    Slimefun.registerResearch(new Research(19, "Стальной век", 11), SlimefunItems.STEEL_INGOT);
	    Slimefun.registerResearch(new Research(20, "Важные ресурсы для питания сети", 12), SlimefunItems.SULFATE, SlimefunItems.POWER_CRYSTAL);
	    Slimefun.registerResearch(new Research(21, "Ваша первая батарея", 10), SlimefunItems.BATTERY);
	    Slimefun.registerResearch(new Research(22, "Стальное покрытие", 14), SlimefunItems.STEEL_PLATE);
	    Slimefun.registerResearch(new Research(23, "Стальной движитель", 14), SlimefunItems.STEEL_THRUSTER);
	    Slimefun.registerResearch(new Research(24, "Парашют", 15), SlimefunItems.PARACHUTE);
	    Slimefun.registerResearch(new Research(25, "Крюк", 15), SlimefunItems.GRAPPLING_HOOK, SlimefunItems.HOOK, SlimefunItems.CHAIN);
	    Slimefun.registerResearch(new Research(26, "Реактивные ранцы", 22), SlimefunItems.DURALUMIN_JETPACK, SlimefunItems.BILLON_JETPACK, SlimefunItems.SOLDER_JETPACK, SlimefunItems.STEEL_JETPACK, SlimefunItems.DAMASCUS_STEEL_JETPACK, SlimefunItems.REINFORCED_ALLOY_JETPACK);
	    Slimefun.registerResearch(new Research(27, "Мультиинструменты", 18), SlimefunItems.DURALUMIN_MULTI_TOOL, SlimefunItems.SOLDER_MULTI_TOOL, SlimefunItems.BILLON_MULTI_TOOL, SlimefunItems.STEEL_MULTI_TOOL, SlimefunItems.DAMASCUS_STEEL_MULTI_TOOL, SlimefunItems.REINFORCED_ALLOY_MULTI_TOOL);
	    Slimefun.registerResearch(new Research(28, "Солнечная энергия", 17), SlimefunItems.SOLAR_PANEL, SlimefunItems.SOLAR_HELMET);
	    Slimefun.registerResearch(new Research(29, "Элементальный посох", 17), SlimefunItems.STAFF_ELEMENTAL);
	    Slimefun.registerResearch(new Research(30, "Измельчитель вещей", 4), SlimefunItems.GRIND_STONE);
	    Slimefun.registerResearch(new Research(31, "Кактусовый костюмчик", 5), SlimefunItems.CACTUS_BOOTS, SlimefunItems.CACTUS_CHESTPLATE, SlimefunItems.CACTUS_HELMET, SlimefunItems.CACTUS_LEGGINGS);
	    Slimefun.registerResearch(new Research(32, "Рудопромывочный лоток", 5), SlimefunItems.GOLD_PAN);
	    Slimefun.registerResearch(new Research(33, "Обложка магической книги", 5), SlimefunItems.MAGICAL_BOOK_COVER);
	    Slimefun.registerResearch(new Research(34, "Новые металлы", 6), SlimefunItems.COPPER_INGOT, SlimefunItems.TIN_INGOT, SlimefunItems.SILVER_INGOT, SlimefunItems.LEAD_INGOT, SlimefunItems.ALUMINUM_INGOT, SlimefunItems.ZINC_INGOT, SlimefunItems.MAGNESIUM_INGOT);
	    Slimefun.registerResearch(new Research(35, "Разрушитель руд", 6), SlimefunItems.ORE_CRUSHER);
	    Slimefun.registerResearch(new Research(36, "Создание бронзы", 8), SlimefunItems.BRONZE_INGOT);
	    Slimefun.registerResearch(new Research(37, "Продвинутые сплавы", 12), SlimefunItems.BILLON_INGOT, SlimefunItems.DURALUMIN_INGOT, SlimefunItems.ALUMINUM_BRASS_INGOT, SlimefunItems.ALUMINUM_BRONZE_INGOT, SlimefunItems.SOLDER_INGOT, SlimefunItems.CORINTHIAN_BRONZE_INGOT, SlimefunItems.BRASS_INGOT);
	    Slimefun.registerResearch(new Research(38, "Создание углерода", 9), SlimefunItems.COMPRESSOR, SlimefunItems.CARBON);
	    Slimefun.registerResearch(new Research(39, "Хлебобулочные изделия", 1), SlimefunItems.WHEAT_FLOUR);
	    Slimefun.registerResearch(new Research(40, "Позолоченные железные доспехи", 16), SlimefunItems.GILDED_IRON_HELMET, SlimefunItems.GILDED_IRON_CHESTPLATE, SlimefunItems.GILDED_IRON_LEGGINGS, SlimefunItems.GILDED_IRON_BOOTS);
	    Slimefun.registerResearch(new Research(41, "Искусственные алмазы", 10), SlimefunItems.COMPRESSED_CARBON, SlimefunItems.CARBON_CHUNK, SlimefunItems.SYNTHETIC_DIAMOND);
	    Slimefun.registerResearch(new Research(42, "Барокамера", 14), SlimefunItems.PRESSURE_CHAMBER);
	    Slimefun.registerResearch(new Research(43, "Синтетические сапфиры", 16), SlimefunItems.SYNTHETIC_SAPPHIRE);
	    Slimefun.registerResearch(new Research(45, "Слиток дамасской стали", 17), SlimefunItems.DAMASCUS_STEEL_INGOT);
	    Slimefun.registerResearch(new Research(46, "Доспехи из дамасской стали", 18), SlimefunItems.DAMASCUS_STEEL_HELMET, SlimefunItems.DAMASCUS_STEEL_CHESTPLATE, SlimefunItems.DAMASCUS_STEEL_LEGGINGS, SlimefunItems.DAMASCUS_STEEL_BOOTS);
	    Slimefun.registerResearch(new Research(47, "Усиленный сплав", 22), SlimefunItems.HARDENED_METAL_INGOT, SlimefunItems.REINFORCED_ALLOY_INGOT);
	    Slimefun.registerResearch(new Research(48, "Карбонадо — \"чёрный алмаз\"", 26), SlimefunItems.RAW_CARBONADO, SlimefunItems.CARBONADO);
	    Slimefun.registerResearch(new Research(50, "Магический верстак", 12), SlimefunItems.MAGIC_WORKBENCH);
	    Slimefun.registerResearch(new Research(51, "Ветряной элементальный посох", 17), SlimefunItems.STAFF_WIND);
	    Slimefun.registerResearch(new Research(52, "Усиленная броня", 26), SlimefunItems.REINFORCED_ALLOY_HELMET, SlimefunItems.REINFORCED_ALLOY_CHESTPLATE, SlimefunItems.REINFORCED_ALLOY_LEGGINGS, SlimefunItems.REINFORCED_ALLOY_BOOTS);
	    Slimefun.registerResearch(new Research(53, "Очиститель руд", 5), SlimefunItems.ORE_WASHER, SlimefunItems.STONE_CHUNK, SlimefunItems.SIFTED_ORE);
	    Slimefun.registerResearch(new Research(54, "Чистое золото", 7), SlimefunItems.GOLD_4K, SlimefunItems.GOLD_6K, SlimefunItems.GOLD_8K, SlimefunItems.GOLD_10K, SlimefunItems.GOLD_12K, SlimefunItems.GOLD_14K, SlimefunItems.GOLD_16K, SlimefunItems.GOLD_18K, SlimefunItems.GOLD_20K, SlimefunItems.GOLD_22K, SlimefunItems.GOLD_24K);
	    Slimefun.registerResearch(new Research(55, "Силиконовая долина", 12), SlimefunItems.SILICON, SlimefunItems.FERROSILICON);
	    Slimefun.registerResearch(new Research(56, "Огненный элементальный посох", 2), SlimefunItems.STAFF_FIRE);
	    Slimefun.registerResearch(new Research(57, "Заводская кирка", 17), SlimefunItems.AUTO_SMELT_PICKAXE);
	    Slimefun.registerResearch(new Research(58, "Обычный талисман", 14), SlimefunItems.TALISMAN);
	    Slimefun.registerResearch(new Research(59, "Талисман кузнеца", 18), SlimefunItems.TALISMAN_ANVIL);
	    Slimefun.registerResearch(new Research(60, "Талисман шахтёра", 18), SlimefunItems.TALISMAN_MINER);
	    Slimefun.registerResearch(new Research(61, "Талисман охотника", 18), SlimefunItems.TALISMAN_HUNTER);
	    Slimefun.registerResearch(new Research(62, "Талисман покорителя лавы", 18), SlimefunItems.TALISMAN_LAVA);
	    Slimefun.registerResearch(new Research(63, "Талисман покорителя воды", 18), SlimefunItems.TALISMAN_WATER);
	    Slimefun.registerResearch(new Research(64, "Талисман ангела", 18), SlimefunItems.TALISMAN_ANGEL);
	    Slimefun.registerResearch(new Research(65, "Талисман пожарного", 18), SlimefunItems.TALISMAN_FIRE);
	    Slimefun.registerResearch(new Research(67, "\"Огненная ситуация\"", 14), SlimefunItems.LAVA_CRYSTAL);
	    Slimefun.registerResearch(new Research(68, "Талисман мага", 20), SlimefunItems.TALISMAN_MAGICIAN);
	    Slimefun.registerResearch(new Research(69, "Талисман путешественника", 20), SlimefunItems.TALISMAN_TRAVELLER);
	    Slimefun.registerResearch(new Research(70, "Талисман воина", 20), SlimefunItems.TALISMAN_WARRIOR);
	    Slimefun.registerResearch(new Research(71, "Талисман рыцаря", 20), SlimefunItems.TALISMAN_KNIGHT);
	    Slimefun.registerResearch(new Research(72, "\"Блестящее железо\"", 11), SlimefunItems.GILDED_IRON);
	    Slimefun.registerResearch(new Research(73, "Фальшивый изумруд", 17), SlimefunItems.SYNTHETIC_EMERALD);
	    Slimefun.registerResearch(new Research(74, "Кольчужная броня", 8), SlimefunItems.CHAINMAIL_HELMET, SlimefunItems.CHAINMAIL_CHESTPLATE, SlimefunItems.CHAINMAIL_LEGGINGS, SlimefunItems.CHAINMAIL_BOOTS);
	    Slimefun.registerResearch(new Research(75, "Талисман вихря", 19), SlimefunItems.TALISMAN_WHIRLWIND);
	    Slimefun.registerResearch(new Research(76, "Талисман волшебника", 22), SlimefunItems.TALISMAN_WIZARD);
	    Slimefun.registerResearch(new Research(77, "Лесной топор", 21), SlimefunItems.LUMBER_AXE);
	    Slimefun.registerResearch(new Research(79, "Костюм химзащиты", 21), SlimefunItems.SCUBA_HELMET, SlimefunItems.HAZMATSUIT_CHESTPLATE, SlimefunItems.HAZMATSUIT_LEGGINGS, SlimefunItems.RUBBER_BOOTS);
	    Slimefun.registerResearch(new Research(80, "Радиоактивные штучки", 30), SlimefunItems.TINY_URANIUM, SlimefunItems.SMALL_URANIUM, SlimefunItems.URANIUM);
	    Slimefun.registerResearch(new Research(81, "Очистка руды", 25), SlimefunItems.CRUSHED_ORE, SlimefunItems.PULVERIZED_ORE, SlimefunItems.PURE_ORE_CLUSTER);
	    Slimefun.registerResearch(new Research(84, "Редстоуновый сплав", 16), SlimefunItems.REDSTONE_ALLOY);
	    Slimefun.registerResearch(new Research(85, "Верхняя планка инструментов", 24), SlimefunItems.CARBONADO_MULTI_TOOL, SlimefunItems.CARBONADO_JETPACK, SlimefunItems.CARBONADO_JETBOOTS);
	    Slimefun.registerResearch(new Research(86, "Первая помощь", 2), SlimefunItems.CLOTH, SlimefunItems.RAG, SlimefunItems.BANDAGE, SlimefunItems.SPLINT, SlimefunItems.CAN, SlimefunItems.VITAMINS, SlimefunItems.MEDICINE);
	    Slimefun.registerResearch(new Research(87, "Блестящие доспехи", 13), SlimefunItems.GOLD_HELMET, SlimefunItems.GOLD_CHESTPLATE, SlimefunItems.GOLD_LEGGINGS, SlimefunItems.GOLD_BOOTS);
	    Slimefun.registerResearch(new Research(89, "Прибор ночного видения", 10), SlimefunItems.NIGHT_VISION_GOGGLES);
	    Slimefun.registerResearch(new Research(90, "Кирка сдерживания", 14), SlimefunItems.PICKAXE_OF_CONTAINMENT, SlimefunItems.BROKEN_SPAWNER);
	    Slimefun.registerResearch(new Research(91, "Геркулесовая кирка", 28), SlimefunItems.HERCULES_PICKAXE);
	    Slimefun.registerResearch(new Research(92, "Лесопилка", 4), SlimefunItems.TABLE_SAW);
	    Slimefun.registerResearch(new Research(93, "Слизистые стальные доспехи", 27), SlimefunItems.SLIME_HELMET_STEEL, SlimefunItems.SLIME_CHESTPLATE_STEEL, SlimefunItems.SLIME_LEGGINGS_STEEL, SlimefunItems.SLIME_BOOTS_STEEL);
	    Slimefun.registerResearch(new Research(94, "Вампирский клинок", 26), SlimefunItems.BLADE_OF_VAMPIRES);
	    Slimefun.registerResearch(new Research(95, "Ленивый шахтёр", 40), SlimefunItems.DIGITAL_MINER);
	    Slimefun.registerResearch(new Research(96, "Водный элементальный посох", 8), SlimefunItems.STAFF_WATER);
	    Slimefun.registerResearch(new Research(97, "\"Эльдорадо\"", 19), SlimefunItems.GOLD_24K_BLOCK);
	    Slimefun.registerResearch(new Research(98, "Продвинутый цифровой шахтёр", 42), SlimefunItems.ADVANCED_DIGITAL_MINER);
	    Slimefun.registerResearch(new Research(99, "Компостирование грязи", 3), SlimefunItems.COMPOSTER);
	    Slimefun.registerResearch(new Research(100, "Фермерские ботинки", 4), SlimefunItems.FARMER_SHOES);
	    Slimefun.registerResearch(new Research(101, "Взрывная кирка", 30), SlimefunItems.EXPLOSIVE_PICKAXE, SlimefunItems.EXPLOSIVE_SHOVEL);
	    Slimefun.registerResearch(new Research(102, "Автоматизированная панорамированная машина", 17), SlimefunItems.AUTOMATED_PANNING_MACHINE);
	    Slimefun.registerResearch(new Research(103, "Сапожки путешественника", 19), SlimefunItems.BOOTS_OF_THE_STOMPER);
	    Slimefun.registerResearch(new Research(104, "Кирка искателя", 19), SlimefunItems.PICKAXE_OF_THE_SEEKER);
	    Slimefun.registerResearch(new Research(105, "Рюкзаки", 15), SlimefunItems.BACKPACK_LARGE, SlimefunItems.BACKPACK_MEDIUM, SlimefunItems.BACKPACK_SMALL);
	    Slimefun.registerResearch(new Research(106, "Тканевой рюкзак", 19), SlimefunItems.WOVEN_BACKPACK);
	    Slimefun.registerResearch(new Research(107, "Тигель", 13), SlimefunItems.CRUCIBLE);
	    Slimefun.registerResearch(new Research(108, "Позолоченный рюкзак", 22), SlimefunItems.GILDED_BACKPACK);
	    Slimefun.registerResearch(new Research(111, "Бронированный реактивный ранец", 27), SlimefunItems.ARMORED_JETPACK);
	    Slimefun.registerResearch(new Research(112, "Эндер-талисманы", 28));
	    Slimefun.registerResearch(new Research(115, "Даже больше руд…", 10), SlimefunItems.NICKEL_INGOT, SlimefunItems.COBALT_INGOT);
	    Slimefun.registerResearch(new Research(116, "Магнитные металлы", 16), SlimefunItems.MAGNET);
	    Slimefun.registerResearch(new Research(117, "Магнит?", 18), SlimefunItems.INFUSED_MAGNET);
	    Slimefun.registerResearch(new Research(118, "Кобальтовая кирка", 14), SlimefunItems.COBALT_PICKAXE);
	    Slimefun.registerResearch(new Research(119, "Некромантия", 19), SlimefunItems.NECROTIC_SKULL, SlimefunItems.ESSENCE_OF_AFTERLIFE);
	    Slimefun.registerResearch(new Research(120, "Персональное хранилище", 22), SlimefunItems.BOUND_BACKPACK);
	    Slimefun.registerResearch(new Research(121, "Рективные ботинки", 25), SlimefunItems.DURALUMIN_JETBOOTS, SlimefunItems.BILLON_JETBOOTS, SlimefunItems.SOLDER_JETBOOTS, SlimefunItems.STEEL_JETBOOTS, SlimefunItems.DAMASCUS_STEEL_JETBOOTS, SlimefunItems.REINFORCED_ALLOY_JETBOOTS);
	    Slimefun.registerResearch(new Research(122, "Бронированные рективные ботинки", 27), SlimefunItems.ARMORED_JETBOOTS);
	    Slimefun.registerResearch(new Research(123, "Сейсмический топор", 29), SlimefunItems.SEISMIC_AXE);
	    Slimefun.registerResearch(new Research(124, "Кирка быстрой добычи", 29), SlimefunItems.PICKAXE_OF_VEIN_MINING);
	    Slimefun.registerResearch(new Research(125, "Персональное оружие", 29), SlimefunItems.SOULBOUND_SWORD, SlimefunItems.SOULBOUND_BOW, SlimefunItems.SOULBOUND_TRIDENT);
	    Slimefun.registerResearch(new Research(126, "Персональные инструменты", 29), SlimefunItems.SOULBOUND_PICKAXE, SlimefunItems.SOULBOUND_AXE, SlimefunItems.SOULBOUND_SHOVEL, SlimefunItems.SOULBOUND_HOE);
	    Slimefun.registerResearch(new Research(127, "Персональная броня", 29), SlimefunItems.SOULBOUND_HELMET, SlimefunItems.SOULBOUND_CHESTPLATE, SlimefunItems.SOULBOUND_LEGGINGS, SlimefunItems.SOULBOUND_BOOTS);
	    Slimefun.registerResearch(new Research(129, "Вкусные напитки", 29), SlimefunItems.JUICER, SlimefunItems.APPLE_JUICE, SlimefunItems.MELON_JUICE, SlimefunItems.CARROT_JUICE, SlimefunItems.PUMPKIN_JUICE, SlimefunItems.SWEET_BERRY_JUICE);
	    Slimefun.registerResearch(new Research(130, "Ремонт спавнеров", 15), SlimefunItems.REPAIRED_SPAWNER);
	    Slimefun.registerResearch(new Research(131, "Хо, хо, хо!", 1));
	    Slimefun.registerResearch(new Research(132, "Продвинутая печь", 7), SlimefunItems.ENHANCED_FURNACE, SlimefunItems.ENHANCED_FURNACE_2);
	    Slimefun.registerResearch(new Research(133, "Улучшенные печи", 18), SlimefunItems.ENHANCED_FURNACE_3, SlimefunItems.ENHANCED_FURNACE_4, SlimefunItems.ENHANCED_FURNACE_5, SlimefunItems.ENHANCED_FURNACE_6, SlimefunItems.ENHANCED_FURNACE_7);
	    Slimefun.registerResearch(new Research(134, "Высокоуровневая печь", 29), SlimefunItems.ENHANCED_FURNACE_8, SlimefunItems.ENHANCED_FURNACE_9, SlimefunItems.ENHANCED_FURNACE_10, SlimefunItems.ENHANCED_FURNACE_11);
	    Slimefun.registerResearch(new Research(135, "Усиленная печь", 32), SlimefunItems.REINFORCED_FURNACE);
	    Slimefun.registerResearch(new Research(136, "Чёрноалмазная печь", 35), SlimefunItems.CARBONADO_EDGED_FURNACE);
	    Slimefun.registerResearch(new Research(137, "\"Нагрев\"", 32), SlimefunItems.ELECTRO_MAGNET, SlimefunItems.ELECTRIC_MOTOR, SlimefunItems.HEATING_COIL);
	    Slimefun.registerResearch(new Research(138, "Размещатель блоков", 17), SlimefunItems.BLOCK_PLACER);
	    Slimefun.registerResearch(new Research(139, "Ленивое планирование", 29), SlimefunItems.AUTOMATED_PANNING_MACHINE);
	    Slimefun.registerResearch(new Research(142, "Поворот вещей вокруг", 38), SlimefunItems.SCROLL_OF_DIMENSIONAL_TELEPOSITION);
	    Slimefun.registerResearch(new Research(143, "\"Робин Гуд\"", 22), SlimefunItems.EXPLOSIVE_BOW, SlimefunItems.ICY_BOW);
	    Slimefun.registerResearch(new Research(144, "Деление с друзьями", 30), SlimefunItems.TOME_OF_KNOWLEDGE_SHARING);
	    Slimefun.registerResearch(new Research(145, "Хранилище опыта", 13), SlimefunItems.FLASK_OF_KNOWLEDGE);
	    Slimefun.registerResearch(new Research(146, "Покорение взрывов", 15), SlimefunItems.REINFORCED_PLATE, SlimefunItems.HARDENED_GLASS);
	    Slimefun.registerResearch(new Research(148, "Счастливой Пасхи!", 1));
	    Slimefun.registerResearch(new Research(149, "\"Золотое зелье\"", 24), SlimefunItems.GOLDEN_APPLE_JUICE);
	    Slimefun.registerResearch(new Research(150, "\"Переносной холодильник\"", 24), SlimefunItems.COOLING_UNIT, SlimefunItems.COOLER);
	    Slimefun.registerResearch(new Research(151, "Древний алтарь", 15), SlimefunItems.ANCIENT_PEDESTAL, SlimefunItems.ANCIENT_ALTAR);
	    Slimefun.registerResearch(new Research(152, "Особый обсидиан", 21), SlimefunItems.WITHER_PROOF_OBSIDIAN);
	    Slimefun.registerResearch(new Research(154, "Улучшенные солнечные панели", 26), SlimefunItems.SOLAR_ARRAY);
	    Slimefun.registerResearch(new Research(155, "Элементальные руны", 15), SlimefunItems.BLANK_RUNE, SlimefunItems.RUNE_EARTH, SlimefunItems.RUNE_WATER, SlimefunItems.RUNE_AIR, SlimefunItems.RUNE_FIRE);
	    Slimefun.registerResearch(new Research(156, "Фиолетовые руны", 18), SlimefunItems.RUNE_ENDER, SlimefunItems.RUNE_RAINBOW);
	    Slimefun.registerResearch(new Research(157, "Незеритовая костная мука", 12), SlimefunItems.INFERNAL_BONEMEAL);
	    Slimefun.registerResearch(new Research(158, "Радужные блоки", 24), SlimefunItems.RAINBOW_CLAY, SlimefunItems.RAINBOW_GLASS, SlimefunItems.RAINBOW_GLASS_PANE, SlimefunItems.RAINBOW_WOOL);
	    Slimefun.registerResearch(new Research(159, "Заряженная воронка", 22), SlimefunItems.INFUSED_HOPPER);
	    Slimefun.registerResearch(new Research(160, "Особое стекло", 20), SlimefunItems.WITHER_PROOF_GLASS);
	    Slimefun.registerResearch(new Research(161, "Скотч", 14), SlimefunItems.DUCT_TAPE);
	    Slimefun.registerResearch(new Research(162, "Пластик", 25), SlimefunItems.PLASTIC_SHEET);
	    Slimefun.registerResearch(new Research(163, "Оперативная память Андроида", 28), SlimefunItems.ANDROID_MEMORY_CORE);
	    Slimefun.registerResearch(new Research(164, "Нефть!", 30), SlimefunItems.BUCKET_OF_OIL, SlimefunItems.OIL_PUMP);
	    Slimefun.registerResearch(new Research(165, "Топливо", 30), SlimefunItems.BUCKET_OF_FUEL, SlimefunItems.REFINERY);
	    Slimefun.registerResearch(new Research(166, "ГоЛоГрАмМы", 36), SlimefunItems.HOLOGRAM_PROJECTOR);
	    Slimefun.registerResearch(new Research(167, "Базовые конденсаторы", 25), SlimefunItems.SMALL_CAPACITOR, SlimefunItems.MEDIUM_CAPACITOR, SlimefunItems.BIG_CAPACITOR);
	    Slimefun.registerResearch(new Research(168, "Продвинутые конденсаторы", 32), SlimefunItems.LARGE_CAPACITOR, SlimefunItems.CARBONADO_EDGED_CAPACITOR);
	    Slimefun.registerResearch(new Research(169, "\"Выращивание солнечной энергии\"", 14), SlimefunItems.SOLAR_GENERATOR);
	    Slimefun.registerResearch(new Research(170, "Электрическая печь", 15), SlimefunItems.ELECTRIC_FURNACE);
	    Slimefun.registerResearch(new Research(171, "Дробление и распыление", 20), SlimefunItems.ELECTRIC_ORE_GRINDER, SlimefunItems.ELECTRIC_INGOT_PULVERIZER);
	    Slimefun.registerResearch(new Research(172, "Обогреваемая барокамераr", 22), SlimefunItems.HEATED_PRESSURE_CHAMBER);
	    Slimefun.registerResearch(new Research(173, "Угольный генератор", 18), SlimefunItems.COAL_GENERATOR);
	    Slimefun.registerResearch(new Research(173, "Биореактор", 18), SlimefunItems.BIO_REACTOR);
	    Slimefun.registerResearch(new Research(174, "Автоматическое зачаровывание и разачаровывание", 24), SlimefunItems.AUTO_ENCHANTER, SlimefunItems.AUTO_DISENCHANTER);
	    Slimefun.registerResearch(new Research(175, "Автоматизированная наковальня", 34), SlimefunItems.AUTO_ANVIL, SlimefunItems.AUTO_ANVIL_2);
	    Slimefun.registerResearch(new Research(176, "Мультиметр", 10), SlimefunItems.MULTIMETER);
	    Slimefun.registerResearch(new Research(177, "Базовая GPS установка", 28), SlimefunItems.GPS_TRANSMITTER, SlimefunItems.GPS_CONTROL_PANEL, SlimefunItems.GPS_MARKER_TOOL);
	    Slimefun.registerResearch(new Research(178, "GPS аварийная точка", 30), SlimefunItems.GPS_EMERGENCY_TRANSMITTER);
	    Slimefun.registerResearch(new Research(179, "Программирование Андроидов", 50), SlimefunItems.PROGRAMMABLE_ANDROID, SlimefunItems.PROGRAMMABLE_ANDROID_FARMER, SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER, SlimefunItems.PROGRAMMABLE_ANDROID_FISHERMAN, SlimefunItems.PROGRAMMABLE_ANDROID_MINER, SlimefunItems.PROGRAMMABLE_ANDROID_WOODCUTTER);
	    Slimefun.registerResearch(new Research(180, "Андроид-интерфейсы", 26), SlimefunItems.ANDROID_INTERFACE_FUEL, SlimefunItems.ANDROID_INTERFACE_ITEMS);
	    Slimefun.registerResearch(new Research(181, "Гоесканирование", 30), SlimefunItems.GPS_GEO_SCANNER, SlimefunItems.PORTABLE_GEO_SCANNER);
	    Slimefun.registerResearch(new Research(182, "Реактор горения", 38), SlimefunItems.COMBUSTION_REACTOR);
	    Slimefun.registerResearch(new Research(183, "Базовые компоненты телепортера", 42), SlimefunItems.GPS_TELEPORTATION_MATRIX, SlimefunItems.GPS_TELEPORTER_PYLON);
	    Slimefun.registerResearch(new Research(184, "Активация телепортера", 36), SlimefunItems.GPS_ACTIVATION_DEVICE_PERSONAL, SlimefunItems.GPS_ACTIVATION_DEVICE_SHARED);
	    Slimefun.registerResearch(new Research(185, "Модернизированные солнечные генераторы", 28), SlimefunItems.SOLAR_GENERATOR_2, SlimefunItems.SOLAR_GENERATOR_3);
	    Slimefun.registerResearch(new Research(186, "Модернизированные передатчики", 36), SlimefunItems.GPS_TRANSMITTER_2, SlimefunItems.GPS_TRANSMITTER_3);
	    Slimefun.registerResearch(new Research(187, "Лифтяные плиты", 28), SlimefunItems.ELEVATOR);
	    Slimefun.registerResearch(new Research(188, "Солнечная энергия круглые сутки!", 44), SlimefunItems.SOLAR_GENERATOR_4);
	    Slimefun.registerResearch(new Research(189, "Высокоуровневый передатчик", 44), SlimefunItems.GPS_TRANSMITTER_4);
	    Slimefun.registerResearch(new Research(190, "Электрические сети", 6), SlimefunItems.ENERGY_REGULATOR);
	    Slimefun.registerResearch(new Research(191, "Андроид-мясник", 32), SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER);
	    Slimefun.registerResearch(new Research(192, "Органическая пища", 25), SlimefunItems.FOOD_FABRICATOR, SlimefunItems.WHEAT_ORGANIC_FOOD, SlimefunItems.CARROT_ORGANIC_FOOD, SlimefunItems.POTATO_ORGANIC_FOOD, SlimefunItems.SEEDS_ORGANIC_FOOD, SlimefunItems.BEETROOT_ORGANIC_FOOD, SlimefunItems.MELON_ORGANIC_FOOD, SlimefunItems.APPLE_ORGANIC_FOOD, SlimefunItems.SWEET_BERRIES_ORGANIC_FOOD);
	    Slimefun.registerResearch(new Research(193, "Автоматизированное размножение", 25), SlimefunItems.AUTO_BREEDER);
	    Slimefun.registerResearch(new Research(194, "Продвинутый Андроид", 60), SlimefunItems.PROGRAMMABLE_ANDROID_2);
	    Slimefun.registerResearch(new Research(195, "Продвинутый Андроид-мясник", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_BUTCHER);
	    Slimefun.registerResearch(new Research(196, "Продвинутый Андроид-рыбак", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_FISHERMAN);
	    Slimefun.registerResearch(new Research(197, "Ускоритель роста животных", 32), SlimefunItems.ANIMAL_GROWTH_ACCELERATOR);
	    Slimefun.registerResearch(new Research(198, "Хранилище опыта", 36), SlimefunItems.XP_COLLECTOR);
	    Slimefun.registerResearch(new Research(199, "Органические удобрения", 36), SlimefunItems.FOOD_COMPOSTER, SlimefunItems.WHEAT_FERTILIZER, SlimefunItems.CARROT_FERTILIZER, SlimefunItems.POTATO_FERTILIZER, SlimefunItems.SEEDS_FERTILIZER, SlimefunItems.BEETROOT_FERTILIZER, SlimefunItems.MELON_FERTILIZER, SlimefunItems.APPLE_FERTILIZER, SlimefunItems.SWEET_BERRIES_FERTILIZER);
	    Slimefun.registerResearch(new Research(200, "Ускорение роста растений", 40), SlimefunItems.CROP_GROWTH_ACCELERATOR);
	    Slimefun.registerResearch(new Research(201, "Модернизированный ускоритель роста растений", 44), SlimefunItems.CROP_GROWTH_ACCELERATOR_2);
	    Slimefun.registerResearch(new Research(202, "Реакторные основы", 36), SlimefunItems.REACTOR_COOLANT_CELL, SlimefunItems.NEPTUNIUM, SlimefunItems.PLUTONIUM);
	    Slimefun.registerResearch(new Research(203, "Атомная электростанция", 48), SlimefunItems.NUCLEAR_REACTOR);
	    Slimefun.registerResearch(new Research(204, "Морозилка", 20), SlimefunItems.FREEZER);
	    Slimefun.registerResearch(new Research(205, "Основы грузовой сети", 30), SlimefunItems.CARGO_MOTOR, SlimefunItems.CARGO_MANAGER, SlimefunItems.CARGO_NODE);
	    Slimefun.registerResearch(new Research(206, "Установка грузовой сети", 30), SlimefunItems.CARGO_INPUT, SlimefunItems.CARGO_OUTPUT);
	    Slimefun.registerResearch(new Research(207, "Электрическая фабрика слитков", 18), SlimefunItems.ELECTRIC_GOLD_PAN, SlimefunItems.ELECTRIC_DUST_WASHER, SlimefunItems.ELECTRIC_INGOT_FACTORY);
	    Slimefun.registerResearch(new Research(208, "Улучшенная электрическая фабрика слитков", 26), SlimefunItems.ELECTRIC_GOLD_PAN_2, SlimefunItems.ELECTRIC_DUST_WASHER_2, SlimefunItems.ELECTRIC_INGOT_FACTORY_2);
	    Slimefun.registerResearch(new Research(209, "Сверхбыстрая электрическая фабрика слитков", 32), SlimefunItems.ELECTRIC_GOLD_PAN_3, SlimefunItems.ELECTRIC_DUST_WASHER_3, SlimefunItems.ELECTRIC_INGOT_FACTORY_3, SlimefunItems.ELECTRIC_ORE_GRINDER_2);
	    Slimefun.registerResearch(new Research(210, "Автоматизированный крафт", 20), SlimefunItems.AUTOMATED_CRAFTING_CHAMBER);
	    Slimefun.registerResearch(new Research(211, "Улучшенная пищевая фабрика", 28), SlimefunItems.FOOD_FABRICATOR_2, SlimefunItems.FOOD_COMPOSTER_2);
	    Slimefun.registerResearch(new Research(212, "Взаимодействие с реактором", 18), SlimefunItems.REACTOR_ACCESS_PORT);
	    Slimefun.registerResearch(new Research(213, "Жидкостный насос", 28), SlimefunItems.FLUID_PUMP);
	    Slimefun.registerResearch(new Research(214, "Улучшенная морозилка", 29), SlimefunItems.FREEZER_2);
	    Slimefun.registerResearch(new Research(215, "\"Замкнутый круг\"", 30), SlimefunItems.BOOSTED_URANIUM);
	    Slimefun.registerResearch(new Research(216, "Мусор", 8), SlimefunItems.TRASH_CAN);
	    Slimefun.registerResearch(new Research(217, "Продвинутый грузовой узел", 24), SlimefunItems.CARGO_OUTPUT_ADVANCED);
	    Slimefun.registerResearch(new Research(218, "Углеродный пресс", 28), SlimefunItems.CARBON_PRESS);
	    Slimefun.registerResearch(new Research(219, "Электрическая плавильня", 28), SlimefunItems.ELECTRIC_SMELTERY);
	    Slimefun.registerResearch(new Research(220, "Модернизированная электропечь", 20), SlimefunItems.ELECTRIC_FURNACE_2, SlimefunItems.ELECTRIC_FURNACE_3);
	    Slimefun.registerResearch(new Research(221, "Улучшенный углеродный пресс", 26), SlimefunItems.CARBON_PRESS_2);
	    Slimefun.registerResearch(new Research(222, "Усиленный программируемый Андроид", 60), SlimefunItems.PROGRAMMABLE_ANDROID_3);
	    Slimefun.registerResearch(new Research(223, "Усиленный программируемый Андроид-мясник", 30), SlimefunItems.PROGRAMMABLE_ANDROID_3_BUTCHER);
	    Slimefun.registerResearch(new Research(224, "Усиленный программируемый Андроид-рыбак", 30), SlimefunItems.PROGRAMMABLE_ANDROID_3_FISHERMAN);
	    Slimefun.registerResearch(new Research(225, "Высокоуровневый углеродный пресс", 32), SlimefunItems.CARBON_PRESS_3);
	    Slimefun.registerResearch(new Research(226, "Иссушающий ассемблер", 35), SlimefunItems.WITHER_ASSEMBLER);
	    Slimefun.registerResearch(new Research(227, "Модернизированная обогреваемая барокамера", 20), SlimefunItems.HEATED_PRESSURE_CHAMBER_2);
	    Slimefun.registerResearch(new Research(228, "Элитры", 20), SlimefunItems.ELYTRA_SCALE, SlimefunItems.ELYTRA);
	    Slimefun.registerResearch(new Research(229, "Особые элитры", 30), SlimefunItems.INFUSED_ELYTRA, SlimefunItems.SOULBOUND_ELYTRA);
	    Slimefun.registerResearch(new Research(230, "Электрический тигель", 26), SlimefunItems.ELECTRIFIED_CRUCIBLE);
	    Slimefun.registerResearch(new Research(231, "Горячие тигли", 30), SlimefunItems.ELECTRIFIED_CRUCIBLE_2, SlimefunItems.ELECTRIFIED_CRUCIBLE_3);
	    Slimefun.registerResearch(new Research(232, "Модернизированная электрическая плавильня", 28), SlimefunItems.ELECTRIC_SMELTERY_2);
	    Slimefun.registerResearch(new Research(233, "Продвинутый Андроид-фермер", 30), SlimefunItems.PROGRAMMABLE_ANDROID_2_FARMER);
	    Slimefun.registerResearch(new Research(234, "Лавовый генератор", 38), SlimefunItems.LAVA_GENERATOR);
	    Slimefun.registerResearch(new Research(235, "Незеритовая ячейка охлаждающей жидкости", 45), SlimefunItems.NETHER_ICE, SlimefunItems.ENRICHED_NETHER_ICE, SlimefunItems.NETHER_ICE_COOLANT_CELL, SlimefunItems.NETHER_DRILL);
	    Slimefun.registerResearch(new Research(236, "Незеритовый звёздный реактор", 60), SlimefunItems.NETHERSTAR_REACTOR);
	    Slimefun.registerResearch(new Research(237, "Раскалённые слитки", 38), SlimefunItems.BLISTERING_INGOT, SlimefunItems.BLISTERING_INGOT_2, SlimefunItems.BLISTERING_INGOT_3);
	    Slimefun.registerResearch(new Research(239, "Автоматическая камера зажигания", 12), SlimefunItems.IGNITION_CHAMBER);
	    Slimefun.registerResearch(new Research(240, "Выходной сундук", 20), SlimefunItems.OUTPUT_CHEST);
	    Slimefun.registerResearch(new Research(241, "Медный провод", 15), SlimefunItems.COPPER_WIRE);
	    Slimefun.registerResearch(new Research(242, "Рюкзак путешественника", 25), SlimefunItems.RADIANT_BACKPACK);
	    Slimefun.registerResearch(new Research(243, "Сухой день", 15), SlimefunItems.AUTO_DRIER);
	    Slimefun.registerResearch(new Research(244, "Диетическое печенье", 3), SlimefunItems.DIET_COOKIE);
	    Slimefun.registerResearch(new Research(245, "Буревой элементальный посох", 30), SlimefunItems.STAFF_STORM);
	    Slimefun.registerResearch(new Research(246, "Персональная руна", 60), SlimefunItems.RUNE_SOULBOUND);
	    Slimefun.registerResearch(new Research(247, "Геокопатель", 24), SlimefunItems.GEO_MINER);
	    Slimefun.registerResearch(new Research(248, "Молниевый элементальный посох", 24), SlimefunItems.RUNE_LIGHTNING);
	    Slimefun.registerResearch(new Research(249, "Тотем бессмертия", 36), SlimefunItems.TOTEM_OF_UNDYING);
		Slimefun.registerResearch(new Research(250, "Зарядное устройство-верстак", 8), SlimefunItems.CHARGING_BENCH);
	    Slimefun.registerResearch(new Research(251, "Незеритовый рудопромывочный лоток", 8), SlimefunItems.NETHER_GOLD_PAN);
	    Slimefun.registerResearch(new Research(252, "Электрический пресс", 16), SlimefunItems.ELECTRIC_PRESS, SlimefunItems.ELECTRIC_PRESS_2);
	}
}
