options:
  # Instead of disabling Auto Updates consider using the "stable" version of Slimefun.
  # These builds are much more tested and are far less likely to have any issues.
  # Note: When running a stable build auto-updates ONLY update to other stable builds! Perfect eh?
  # You can download the latest stable build here: https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/stable/
  auto-update: false
  armor-update-interval: 10
  give-guide-on-first-join: true
  print-out-loading: false
  print-out-github-data-retrieving: false
  enable-armor-effects: true
  prefix: '&a&lSlimefun &7>'
  auto-save-delay-in-minutes: 10
  show-vanilla-recipes-in-guide: true
  allow-free-creative-research: true
  emerald-enchantment-limit: 2
  research-unlock-fireworks: true
  research-give-fireworks: true
  legacy-ore-washer: false
  legacy-dust-washer: false
  legacy-ore-grinder: true
guide:
  default-view-book: false
URID:
  info-delay: 3000
  custom-ticker-delay: 12
  enable-tickers: true
items:
  talismans: true
  coolers: true
  backpacks: true
research-ranks:
  - Курица | I
  - Коровушка | II
  - Паучок | III
  - Крестьянин | IV
  - Начинающий | V
  - Неуклюжий студент | VI
  - Неумелый студент | VII
  - Некомпетентный студент | VIII
  - Студент | IIX
  - Неуклюжий подмастер | IX
  - Подмастер | X
  - Умелый подмастер | XI
  - Хороший маг | XII
  - Отличный маг | XIII
  - Молодой фокусник | XIV
  - Некомпетентный фокусник | XV
  - Средний фокусник | XVI
  - Фокусник | XVII
  - Опытный фокусник | XVIII
  - Искусный фокусник | XIX
  - Привыкший фокусник | XX
  - Великий фокусник | XXI
  - Неуклюжий волшебник | XXII
  - Волшебник | XXIII
  - Опытный волшебник | XXIV
  - Впечатляющий волшебник | XXV
  - Великий волшебник | XXVI
  - Признанный волшебник | XXVII
  - Будущий мастер | XXVIII
  - Молодой мастер | XXIX
  - Неуклюжий мастер | XXX
  - Компетентный мастер | XXXI
  - Мастер | XXXII
  - Опытный мастер | XXXIII
  - Великий мастер | XXXIV
  - Мудрейший мастер | XXXV
  - Учитель | XXXVI
  - Избранный | MAX
