name: Slimefun
version: ${project.version}
author: Сообщество Slimefun 4
description: Slimefun добавляет просто огромное количество новых предметов без каких-либо модов!
website: https://github.com/TheBusyBiscuit/Slimefun4

main: me.mrCookieSlime.Slimefun.SlimefunPlugin
softdepend: [CS-CoreLib, PlaceholderAPI]

api-version: 1.14

commands:
  slimefun:
    description: Базовая команда
    aliases: sf
    usage: /sf <аргумент>
permissions:
  slimefun.cheat.items:
    description: Разрешение на выдачу предметов
    default: op
  slimefun.cheat.researches:
    description: Разрешение на выдачу достижений
    default: op
  slimefun.stats.others:
    description: Разрешение на просмотр статистики других игроков
    default: op
  slimefun.android.upload-script:
    description: Разрешение на загрузку своего скрипта для Андроида
    default: op
  slimefun.command.timings:
    description: Разрешение на /sf timings
    default: op
  slimefun.command.teleporter:
    description: Разрешение на /sf teleporter
    default: op
  slimefun.command.versions:
    description: Разрешение на /sf versions
    default: op
  slimefun.command.guide:
    description: Разрешение на получение руководства Slimefun
    default: true
  slimefun.command.search:
    description: Разрешение на /sf search
    default: true
  slimefun.command.open_guide:
    description: Разрешение на открытие руководства Slimefun без книги
    default: op
  slimefun.android.bypass:
    description: Разрешение на редактирование чужих Андроидов
    default: op
  slimefun.cargo.bypass:
    description: Разрешение на редактирование грузовых блоков других игроков
    default: op
  slimefun.inventory.bypass:
    description: Разрешение на открытие инвентарей всех механизмов
    default: op
