on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign_labels:
    runs-on: ubuntu-latest
    name: Categorize Pull Requests
    steps:
    - name: Branch Categorization
      uses: TheBusyBiscuit/branch-cat@v1.0.4
      with:
        rules: '{ "fix\/.+" : "Bug Fix" }'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
